### PR TITLE
Add requirements to setup.py

### PR DESCRIPTION
**Pull request by nils-werner**

### CODE REVIEW

**Comment by dfm** [comment]
Thanks but pypdf and pil are only optional dependencies so they shouldn't go into the setup.py! I'd be happy to include matplotlib.

**Comment by nils-werner** [comment]
I disagree, without installed dependencies the bevhaviour of savefig is all over the place:

Without Pillow

```
plt.savefig("out.png")
```

works, but warns about Pillow missing and fails to inject metadata.

Without PyPDF2

```
plt.savefig("out.pdf")
```

works fine and metadata gets injected in to the PDF.

But then, when trying to read the metadata, without Pillow

```
$ python -m savefig out.png
```

results in a totally cryptic error message that does not convey what went wrong:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/nwerner/Arbeit/mdct/lib/python2.7/site-packages/savefig.py", line 255, in <module>
    info = get_file_info(args.filename)
  File "/Users/nwerner/Arbeit/mdct/lib/python2.7/site-packages/savefig.py", line 147, in get_file_info
    img = Image.open(fn)
AttributeError: 'NoneType' object has no attribute 'open'
```

and similarily without PyPDF2

```
$ python -m savefig out.pdf
```

You get yet another error message that isn't helpful

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/nwerner/Arbeit/mdct/lib/python2.7/site-packages/savefig.py", line 255, in <module>
    info = get_file_info(args.filename)
  File "/Users/nwerner/Arbeit/mdct/lib/python2.7/site-packages/savefig.py", line 151, in get_file_info
    pdf = PdfFileReader(f)
TypeError: 'NoneType' object is not callable
```

I can see that you want to have optional dependencies for when you are only saving metadata however I find the resulting behaviour not very reassuring.

Firstly, if you want to only install the minimum set of dependencies for writing, you should at least define all dependencies that are required to fully support writing for all available file types (declare pillow as a dependency).

Secondly, you demand of the user to find out the dependencies manually. This is especially demanding as the reading mode gives no useful help at all, there is no mention of dependencies in the `README.md` and one needs to go through the code to find the right one. So additionally you should at least clean up the error messages and [add all dependencies to a `reading` extra](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies), so that optional dependencies can be precisely defined and quickly installed.

Thirdly, the library isn't that big and doesn't have that many different usecases that having distinct classes of dependencies is really required. Think IPython, where separating out dependencies for notebooks really make sense as there are many non-trivial dependencies for a usecase not everybody needs. You don't need all of that here, really.

So I would just go for the principle of least surprise: You do

```
pip install savefig
```

and get a fully functioning library.

**Comment by dfm** [comment]
OK fair enough! Those errors are really stupid. I'm always hesitant to add dependencies to setup.py because I prefer to use conda for package management but you've convinced me :-)

Thanks!

**Comment by nils-werner** [comment]
Glad I could help :-) I think if you installed all deps using conda, pip should just say "requirement already satisfied" and only install savefig.

**Comment by dfm** [comment]
Definitely but it's a pain when you install something using pip and then realize that you should have installed all the other deps with conda first. The Python packaging system is so broken!

**Pull request merged**
